#ifndef __LIBGAME_MAP_H__
#define __LIBGAME_MAP_H__

#include <stdint.h>
#include <stdbool.h>
#include "wad.h"

// Macro to define a collection of elements (pointer and count)
#define DEFINE_COLLECTION(type, name) \
  type* name;                   \
  int num_##name

// Macro to free a collection and reset its values
#define CLEAR_COLLECTION(map, name) \
  if ((map)->name) free((map)->name); \
  (map)->name = NULL;               \
  (map)->num_##name = 0

// Helper macros for min/max if not already defined
#ifndef MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#endif

#ifndef MAX
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#endif

// Lump order in a map WAD
enum
{
  ML_LABEL,       // A separator, name, ExMx or MAPxx
  ML_THINGS,      // Monsters, items..
  ML_LINEDEFS,    // LineDefs, from editing
  ML_SIDEDEFS,    // SideDefs, from editing
  ML_VERTEXES,    // Vertices, edited and BSP splits generated
  ML_SEGS,        // LineSegs, from LineDefs split by BSP
  ML_SSECTORS,    // SubSectors, list of LineSegs
  ML_NODES,       // BSP nodes
  ML_SECTORS,     // Sectors, from editing
  ML_REJECT,      // LUT, sector-sector visibility
  ML_BLOCKMAP     // LUT, motion clipping, walls/grid element
};

// Indicate a leaf node in BSP
#define NF_SUBSECTOR 0x8000

// Vertex structure
typedef struct {
  int16_t x;                 // X coordinate
  int16_t y;                 // Y coordinate
} mapvertex_t;

// Sidedef structure
typedef struct {
  int16_t textureoffset;     // X offset for texture
  int16_t rowoffset;         // Y offset for texture
  texname_t toptexture;      // Name of upper texture
  texname_t bottomtexture;   // Name of lower texture
  texname_t midtexture;      // Name of middle texture
  uint16_t sector;           // Sector number this sidedef faces
} mapsidedef_t;

// Sector structure
typedef struct {
  int16_t floorheight;       // Floor height
  int16_t ceilingheight;     // Ceiling height
  texname_t floorpic;        // Name of floor texture
  texname_t ceilingpic;      // Name of ceiling texture
  int16_t lightlevel;        // Light level
  int16_t special;           // Special behavior
  int16_t tag;               // Tag number
} mapsector_t;

// BSP node structure
typedef struct {
  // Partition line from (x,y) to x+dx,y+dy)
  int16_t    x;
  int16_t    y;
  int16_t    dx;
  int16_t    dy;
  // Bounding box for each child,
  // clip against view frustum.
  int16_t    bbox[2][4];
  // If NF_SUBSECTOR its a subsector,
  // else it's a node of another subtree.
  uint16_t   children[2];
} mapnode_t;

// SubSector, as generated by BSP.
typedef struct {
  uint16_t    numsegs;
  // Index of first one, segs are stored sequentially.
  uint16_t    firstseg;
} mapsubsector_t;

// Seg structure
typedef struct {
  uint16_t v1;
  uint16_t v2;
  uint16_t angle;
  uint16_t linedef;
  uint16_t side;
  uint16_t offset;
} mapseg_t;

// Conditional compilation for DOOM vs Hexen thing/linedef formats
#ifdef HEXEN
// Hexen Thing structure
typedef struct {
  int16_t tid;
  int16_t x;
  int16_t y;
  int16_t height;
  int16_t angle;
  int16_t type;
  int16_t options;
  int8_t special;
  int8_t args[5];
} mapthing_t;

// Hexen Linedef structure
typedef struct {
  uint16_t start;             // Start vertex
  uint16_t end;               // End vertex
  uint16_t flags;             // Flags
  uint8_t special;            // Special type
  uint8_t args[5];            // Arguments for special (e.g., script number, delay)
  uint16_t sidenum[2];        // Sidedef numbers
} maplinedef_t;
#else
// DOOM Thing structure
typedef struct {
  int16_t x;                 // X position
  int16_t y;                 // Y position
  int16_t angle;             // Angle facing
  int16_t type;              // Thing type
  int16_t flags;             // Flags
} mapthing_t;

// DOOM Linedef structure
typedef struct {
  uint16_t start;             // Start vertex
  uint16_t end;               // End vertex
  uint16_t flags;             // Flags
  uint16_t special;           // Special type
  uint16_t tag;               // Tag number
  uint16_t sidenum[2];        // Sidedef numbers
} maplinedef_t;
#endif

// Map data structure (basic game data without rendering extensions)
// If the application defines MAP_DATA_T_DEFINED, it provides its own extended version
#ifndef MAP_DATA_T_DEFINED
typedef struct {
  DEFINE_COLLECTION(mapvertex_t, vertices);
  DEFINE_COLLECTION(maplinedef_t, linedefs);
  DEFINE_COLLECTION(mapsidedef_t, sidedefs);
  DEFINE_COLLECTION(mapthing_t, things);
  DEFINE_COLLECTION(mapsector_t, sectors);
  DEFINE_COLLECTION(mapnode_t, nodes);
  DEFINE_COLLECTION(mapsubsector_t, subsectors);
  DEFINE_COLLECTION(mapseg_t, segs);
} map_data_t;
#endif

// Map loading functions
map_data_t load_map(const char* map_name);
void free_map_data(map_data_t* map);
void print_map_info(map_data_t* map);

#endif // __LIBGAME_MAP_H__
